# This workflow will build a Go project

name: Go

on:
  push:
    branches: [ "goplus" ]
  pull_request:
    branches: [ "goplus" ]

jobs:
  Test:
    strategy:
      matrix:
        go-version: [1.18.x, 1.21.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go/Go+
      uses: goplus/setup-goplus@v1.1.0
      with:
        go-version: ${{ matrix.go-version }}
        gop-version: "1.1.13"
        check-latest: true
        cache: true

    - name: Build Go+ tools
      run: |
        cd gop
        go build -v ./...

    - name: Test Go+ tools
      run: |
        cd gop
        go test -v -coverprofile="coverage.txt" -covermode=atomic ./...

    - name: Build Goxls
      run: |
        cd gopls
        go build -v ./...

    - name: Test Goxls
      run: |
        cd gopls
        go test -v ./...

    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./gop/coverage.txt
